### ISSUE TITLE
Evaluation metrics function

### ISSUE THREAD

**Issue by aamirk5** [TrinhSaiki/Edited_Original_IDCGAN#1]
Hello Sir,,,
I'm learning deraining. Could you please help me out in these matters.. How did you calculate these evaluation metric SSIM, UQI and VIF ? 
if you have any formula or code to calculate these please do share it with me. it'd much appreciated... thanks.. my email id is:
aamir.uettaxila@gmail.com

**Comment by TrinhQuocNguyen** [comment]
Hi Aamirk
I have used another repo to measure the image quality (in C++)
https://github.com/TrinhQuocNguyen/VQMT_VisualStudioProject_ImageQualityMetric
